export interface AssestObj {
    idAssets: number,
    nameAssets: string,
    descptAssets: string,
    typeAssets: string,
    serialAssets: string,
    internalNumAssets: string,
    weightAssets: string,
    heightAssets: string,
    widthAssets: string,
    valueBuyAssets: string,
    dateBuyAssets: string,
    dateLowAssets: string,
    idStatus: string,
    nameStatus: string,
    colourAssets: string,
    idTypeAss: string,
    nameTypeAss: string,
    idAsig: string,
    nameAsig: string
}